{{- if .Values.deployPostgres }}

apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.secrets.name}}
  namespace: {{ .Values.namespace }}
type: Opaque
data:
  POSTGRES_USER: {{ .Values.postgres.user | b64enc }}
  POSTGRES_PASSWORD: {{ .Values.postgres.password | b64enc }}
  POSTGRES_DB: {{ .Values.postgres.db | b64enc }}
{{- end }}